import React, { useEffect, useRef, useState } from 'react';
import JSGantt from 'react-jsgantt';

import styles from './index.less';

const temp = [
  {
    pID: 1,
    pName: '文书',
    pStart: '',
    pEnd: '',
    pClass: styles.ewellParent,
    pLink: '',
    pMile: 0,
    pComp: 0,
    pGroup: 1,
    pParent: 0,
    pOpen: 1,
    pDepend: '',
    pCaption: '',
    pNotes: '',
  },
  {
    pID: 111,
    pName: '文书',
    pStart: '2019-03-20',
    pEnd: '2019-03-26',
    pClass: styles.ewellClass,
    pLink: '',
    pMile: 0,
    pComp: 0,
    pGroup: 0,
    pParent: 1,
    pOpen: 1,
    pDepend: '',
    pCaption: '',
    pNotes: '',
  },
  {
    pID: 34,
    pName: '文书',
    pStart: '',
    pEnd: '',
    pClass: styles.ewellClass,
    pLink: '',
    pMile: 0,
    pComp: 67,
    pGroup: 1,
    pParent: '',
    pOpen: 1,
    pDepend: '',
    pCaption: '',
    pNotes: '',
  },
  {
    pID: 3,
    pName: '体征',
    pStart: '',
    pEnd: '',
    pClass: styles.ewellClass,
    pLink: '',
    pMile: 0,
    pComp: 0,
    pGroup: 1,
    pParent: 0,
    pOpen: 1,
    pDepend: '',
    pCaption: '',
  },
  {
    pID: 31,
    pName: '体温',
    pStart: '2019-06-25',
    pEnd: '2019-07-17',
    pPlanStart: '2019-06-24',
    pPlanEnd: '2019-07-15 12:00',
    // "pClass": styles.ewellClass,
    pClass: 'gtaskred',
    pLink: '',
    pMile: 0,
    pComp: 30,
    pGroup: 0,
    pParent: 3,
    pOpen: 1,
    pDepend: '',
    pCaption: '',
    pNotes: '',
  },
  {
    pID: 32,
    pName: '血压',
    pStart: '2019-07-15 00:00',
    pEnd: '2019-07-16 00:00',
    pClass: styles.ewellClass,
    pLink: '',
    pMile: 0,
    pComp: 0,
    pGroup: 0,
    pParent: 3,
    pOpen: 1,
    pDepend: '',
    pCaption: '',
    pNotes: '',
  },
  {
    pID: 33,
    pName: '脉搏',
    pStart: '',
    pEnd: '',
    pClass: styles.ewellClass,
    pLink: '',
    pMile: 0,
    pComp: 40,
    pGroup: 2,
    pParent: 3,
    pOpen: 1,
    pDepend: '',
    pCaption: '',
    pNotes: '',
  },
  {
    pID: 332,
    pName: '脉搏1',
    pStart: '2019-07-06',
    pEnd: '2019-07-09',
    pClass: styles.ewellClass,
    pLink: '',
    pMile: 0,
    pRes: 'Mario',
    pComp: 0,
    pGroup: 0,
    pParent: 33,
    pOpen: 1,
    pDepend: '',
    pCaption: '',
    pNotes: '',
  },
  {
    pID: 333,
    pName: '脉搏2',
    pStart: '2019-07-11',
    pEnd: '2019-07-20',
    pClass: styles.ewellClass,
    pLink: '',
    pMile: 0,
    pRes: 'Mario',
    pComp: 0,
    pGroup: 0,
    pParent: 33,
    pOpen: 1,
    pDepend: '',
    pCaption: '',
    pNotes: '',
  },

  {
    pID: 341,
    pName: '入院记录单',
    pStart: '2019-03-26',
    pEnd: '2019-04-11',
    pClass: styles.ewellClass,
    pLink: '',
    pMile: 0,
    pComp: 60,
    pGroup: 0,
    pParent: 34,
    pOpen: 1,
    pDepend: '',
    pCaption: '',
    pNotes: '',
  },
  {
    pID: 'A342',
    pName: '入院评估单',
    pStart: '2019-04-12',
    pEnd: '2019-04-14',
    pClass: styles.ewellClass,
    pLink: '',
    pMile: 0,
    pComp: 60,
    pGroup: 0,
    pParent: 34,
    pOpen: 1,
    pDepend: '',
    pCaption: '',
    pNotes: '',
  },
  {
    pID: 343,
    pName: '疼痛评分',
    pStart: '2019-05-13',
    pEnd: '2019-05-17',
    pClass: styles.ewellClass,
    pLink: '',
    pMile: 0,
    pComp: 60,
    pGroup: 0,
    pParent: 34,
    pOpen: 1,
    pDepend: '',
    pCaption: '',
    pNotes: '',
  },
  {
    pID: 344,
    pName: '术前评估1',
    pStart: '2019-06-01',
    pEnd: '2019-06-04',
    pClass: styles.ewellClass,
    pLink: '',
    pMile: 0,
    pComp: 60,
    pGroup: 0,
    pParent: 34,
    pOpen: 1,
    pDepend: '',
    pCaption: '',
    pNotes: '',
  },
];

export default function Example(props) {
  const tooltipDelay = value => {
    console.log('tooltipDelay -> value', value);
    return false;
  };

  const ganttRef = useRef();
  const [data, setData] = useState(temp);
  const [editorOptions, setEditorOptions] = useState({
    vCaptionType: 'None', // Set to Show Caption : None,Caption,Resource,Duration,Complete,
    vQuarterColWidth: 40,
    vDateTaskDisplayFormat: 'day dd month  yyyy', // Shown in tool tip box
    vLang: 'cn',
    vWeekMinorDateDisplayFormat: 'dd mon',
    vResources: 0,
    vFormatArr: ['Minute', 'Hour', 'Day', 'Week', 'Month', 'Quarter'],
    vTooltipTemplate: item => {
      console.log(
        'Example -> valu -当前tooltip对应的所有数据--',
        item.getAllData(),
      );
      return `
        <ul class="tooltipBody">
          <li class="tooltipLi">{{pName}}</li>
        </ul>
      `;
    },
  });

  return (
    <div className={styles.gantt}>
      <JSGantt data={data} options={editorOptions} ref={ganttRef} />
    </div>
  );
}
